# Generated by Django 5.1.7 on 2025-05-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
