# Generated by Django 5.1.7 on 2025-05-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('BOG', 'Bogotá'), ('MED', 'Medellín'), ('CAL', 'Cali'), ('BQU', 'Barranquilla'), ('CTG', 'Cartagena'), ('OTR', 'Otra')], max_length=20, null=True, verbose_name='Ciudad'),
        ),
    ]
