# Generated by Django 5.1.7 on 2025-05-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('BOG', 'Bogotá'), ('MED', 'Medellín'), ('CAL', 'Cali'), ('BQU', 'Barranquilla'), ('CTG', 'Cartagena'), ('JAM', 'Jamundí'), ('PST', 'Pasto'), ('CUN', 'Cúcuta'), ('BAY', 'Bucaramanga'), ('SAM', 'Santa Marta'), ('PER', 'Pereira'), ('SAN', 'Santander de Quilichao'), ('TUN', 'Tunja'), ('OTR', 'Otra')], max_length=3, null=True, verbose_name='Ciudad'),
        ),
    ]
